// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimmeMqqt.EntityFramework;

#nullable disable

namespace SimmeMqqt.Migrations
{
    [DbContext(typeof(MachineData))]
    [Migration("20220322160937_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SimmeMqqt.Model.MQTTMachineData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Break")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Failure")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdealCyclus")
                        .HasColumnType("int");

                    b.Property<int>("MachineID")
                        .HasColumnType("int");

                    b.Property<string>("MachineName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<int>("TotalGoodProduction")
                        .HasColumnType("int");

                    b.Property<int>("TotalProduction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MachineDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
